spring.config.import=optional:file:.env[.properties],optional:file:./BackEnd/.env[.properties]

# → Conexão “normal” ao seu DB-alvo (ex: rede_social)
spring.datasource.url=jdbc:postgresql://localhost:5432/Appmoove_pets_teste
# o meu username é postgres e minha senha é Enquebravel11 . (caso vcs queiram saber)
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_ROOT_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# outros
spring.application.name=BackEnd
server.port=8087

# vars da api
minha.aplicacao.api-key-dog=${API_KEY_DOG}
minha.aplicacao.api-key-cat=${API_KEY_CAT}


# → Hibernate criará/atualizará o schema automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# Permitir conexões de qualquer IP
server.address:0.0.0.0
# tirar isso depois cacete.

